FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# --- Production storage ---
FROM nginx:stable-alpine

# Copy built files from Node to NGINX HTLM dirrectory
COPY --from=build /app/dist /usr/share/nginx/html
COPY public/env.template.js /usr/share/nginx/html/env.template.js

# Replace variables at runtime
CMD sh -c "envsubst < /usr/share/nginx/html/env.template.js > /usr/share/nginx/html/env.js && nginx -g 'daemon off;'"

# Expose nginx port
EXPOSE 80