FROM golang:1.24-alpine AS build

WORKDIR /app

# Copy dependency filess first
COPY go.mod go.sum ./
RUN go mod download

# Now copy full source
COPY . .

# Build binary
RUN go build -o api-golang

# Production stage
FROM alpine:latest

WORKDIR /app
COPY --from=build /app/api-golang .

EXPOSE 8080
CMD [ "./api-golang" ]